### ISSUE TITLE
Connection manage

### ISSUE THREAD

**Issue by mamkin-itshnik** [mamkin-itshnik/penguin-fenix-game-server#1]
Need keep only alive connections in package "main"

- [ ]  Make queue for connected clients named "waitingClients" ( play queue for new players and game overed players like "FIFO" )

- [ ] Make list for connected clients named "playingClients" (this playing guys)

- [ ] Design managing signals(tcp read write data) and API ( main <-> gameCore)  (new game, loose game, connection lost, etc.) 

- [ ] Design bot API

**Comment by twxh563** [comment]
> Need keep only alive connections in package "main"
> 
> * [x]   Make queue for connected clients named "waitingClients" ( play queue for new players and game overed players like "FIFO" ) - **don't need it**
> * [x]  Make list for connected clients named "playingClients" (this playing guys)
> * [x]  Design managing signals(tcp read write data) and API ( main <-> gameCore)  (new game, loose game, connection lost, etc.)
> * [x]  Design bot API

**Comment by mamkin-itshnik** [comment]
done
