### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by mamkin-itshnik** [mamkin-itshnik/penguin-fenix-game-server#3]
**I connect on my machine to server, after connection -> disconnect (repeat several)**
**-look the console log**

`F:\PROJECTs\UNITY\temp_pro\server-side-shit\try_roll_on_GO\pinguin-fenix-game-server>go run servak.go 192.168.0.105:55555
2020/08/24 23:28:35 try starting server on 192.168.0.105:55555
server START on  192.168.0.105:55555
new client add!, now count =  1
2020/08/24 23:28:39 accepted connection from  192.168.0.105:51384
2020/08/24 23:28:39 clients count now =  1
new client add!, now count =  2
2020/08/24 23:29:42 accepted connection from  192.168.0.105:51392
2020/08/24 23:29:42 clients count now =  2
new client add!, now count =  3
2020/08/24 23:30:45 accepted connection from  192.168.0.105:51395
2020/08/24 23:30:45 clients count now =  3
new client add!, now count =  4
2020/08/24 23:31:00 accepted connection from  192.168.0.105:51398
2020/08/24 23:31:00 clients count now =  4
new client add!, now count =  5
fatal error: concurrent map iteration and map write
2020/08/24 23:31:38 accepted connection from  192.168.0.105:51408
2020/08/24 23:31:38 clients count now =  5

goroutine 7 [running]:
runtime.throw(0x51ac61, 0x26)
        c:/go/src/runtime/panic.go:1116 +0x79 fp=0xc000051d90 sp=0xc000051d60 pc=0x434839
runtime.mapiternext(0xc000051f58)
        c:/go/src/runtime/map.go:853 +0x559 fp=0xc000051e10 sp=0xc000051d90 pc=0x40f339
_/F_/PROJECTs/UNITY/temp_pro/server-side-shit/try_roll_on_GO/pinguin-fenix-game-server/gameCore.gameCore.ReadClientsData(0xc000182000)
        F:/PROJECTs/UNITY/temp_pro/server-side-shit/try_roll_on_GO/pinguin-fenix-game-server/gameCore/gameCore.go:91 +0x98 fp=0xc000051fc8 sp=0xc000051e10 pc=0x4d4698
main.reciveDataFromClient()
        F:/PROJECTs/UNITY/temp_pro/server-side-shit/try_roll_on_GO/pinguin-fenix-game-server/servak.go:48 +0x39 fp=0xc000051fe0 sp=0xc000051fc8 pc=0x4d6c59
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000051fe8 sp=0xc000051fe0 pc=0x460b01
created by main.main
        F:/PROJECTs/UNITY/temp_pro/server-side-shit/try_roll_on_GO/pinguin-fenix-game-server/servak.go:65 +0x9e

goroutine 1 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0x61a140)
        c:/go/src/runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0x61a138)
        c:/go/src/sync/waitgroup.go:130 +0x6b
main.main()
        F:/PROJECTs/UNITY/temp_pro/server-side-shit/try_roll_on_GO/pinguin-fenix-game-server/servak.go:68 +0xc6

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x26814ee8, 0x72, 0x537c00)
        c:/go/src/runtime/netpoll.go:203 +0x5c
internal/poll.(*pollDesc).wait(0xc0000c21c8, 0x72, 0x5d7200, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.(*ioSrv).ExecIO(0x5ed9c8, 0xc0000c2018, 0xc0003bc000, 0x1, 0x0, 0x344)
        c:/go/src/internal/poll/fd_windows.go:228 +0x121
internal/poll.(*FD).acceptOne(0xc0000c2000, 0x344, 0xc000120000, 0x2, 0x2, 0xc0000c2018, 0xc0002abd20, 0x4a7404, 0xc000112500, 0xc000116080)
        c:/go/src/internal/poll/fd_windows.go:896 +0xa9
internal/poll.(*FD).Accept(0xc0000c2000, 0xc0002abe00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        c:/go/src/internal/poll/fd_windows.go:930 +0x15f
net.(*netFD).accept(0xc0000c2000, 0xc000116080, 0xc00005c080, 0x5eec00)
        c:/go/src/net/fd_windows.go:193 +0x7b
net.(*TCPListener).accept(0xc000094240, 0x2, 0xc0000102c0, 0x17)
        c:/go/src/net/tcpsock_posix.go:139 +0x39
net.(*TCPListener).Accept(0xc000094240, 0x2, 0x2, 0xc000014020, 0x4)
        c:/go/src/net/tcpsock.go:261 +0x6b
main.startServer(0xc0000103c0, 0x13, 0x0, 0x0)
        F:/PROJECTs/UNITY/temp_pro/server-side-shit/try_roll_on_GO/pinguin-fenix-game-server/servak.go:32 +0x226
created by main.main
        F:/PROJECTs/UNITY/temp_pro/server-side-shit/try_roll_on_GO/pinguin-fenix-game-server/servak.go:63 +0x86

goroutine 8 [sleep]:
time.Sleep(0x5f5e100)
        c:/go/src/runtime/time.go:188 +0xc8
main.sendDataaToClient()
        F:/PROJECTs/UNITY/temp_pro/server-side-shit/try_roll_on_GO/pinguin-fenix-game-server/servak.go:55 +0x46
created by main.main
        F:/PROJECTs/UNITY/temp_pro/server-side-shit/try_roll_on_GO/pinguin-fenix-game-server/servak.go:66 +0xb6
exit status 2

F:\PROJECTs\UNITY\temp_pro\server-side-shit\try_roll_on_GO\pinguin-fenix-game-server>`

**Comment by twxh563** [comment]
fixed, isn't it?
